config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :discussions do
    resources :replies
  end
  
  root to: "discussions#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :discussions
  has_many :users, through: :discussions
  resourcify

  extend FriendlyId
  friendly_id :channel, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    channel_changed?
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @discussions = Discussion.where('channel_id = ?', @channel.id) #Akan menampilkan seluruh diskusi pada sebuah channel
    @channels = Channel.all
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channels_path, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to channel_path(@channel), notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:channel)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :channel, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
    </div>
  </div>

<%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/channels/edit.html.erb
<h1 class="title is-3">Editing Channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/index.html.erb
<h1 class="title is-2">Channels</h1>

<% if has_role?(:admin) %>
<div class="level">
  <div class="level-left"></div>
  <div class="level-right">
    <%= link_to 'New Channel', new_channel_path, class:'button is-dark' %>
  </div>
</div>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |channel| %>
    <tr>
      <td><%= link_to channel.channel, channel %></td>
      <td>
        <div class="buttons is-right">
          <%= link_to 'View Channel', channel, class:'button' %>
          <%= link_to 'Edit Channel', edit_channel_path(channel), class:'button' %>
          <%= link_to 'Delete', channel, class:'button is-danger', method: :delete, data: { confirm: "Are you sure you want to delete this channel? " } %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<% else %>
 <p class="has-text-center">Sorry! You don't have access this page.</p>
<% end %>

app/views/channels/new.html.erb
<div class="columns is-centered">
  <div class="column is-4">
    <h1 class="title is 3">Create a new channel</h1>
    <%= render 'form', channel: @channel %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="level">
  <div class="level-left">
    <h2 class="title is-2"><%= @channel.channel %></h2>
  </div>
  <div class="level-right">
    <% if has_role?(:admin) %>
      <%= link_to 'Edit Channel', edit_channel_path(@channel), class:"button" %>
      <% end %>
  </div>
</div>

<hr>

<div class="columns">
  <%= render 'shared/discussions' %>
  <%= render 'discussions/sidebar' %>
</div>
<hr>