config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :discussions do
    resources :replies
  end
  
  root to: "discussions#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
  validates :reply, presence: true

  extend FriendlyId
  friendly_id :reply, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    reply_changed?
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reply, only: [:edit, :update, :show, :destroy]
  before_action :set_discussion, only: [:create, :edit, :show, :update, :destroy]

  def new

  end

  def create
     @reply = @discussion.replies.create(reply_params)
     @reply.user_id = current_user.id

     respond_to do |format|
       if @reply.save
         format.html { redirect_to discussion_path(@discussion) }
         format.js # renders create.js.erb
       else
         format.html { redirect_to discussion_path(@discussion), notice: "Reply did not save. Please try again."}
         format.js
       end
     end
   end

   def destroy
     @reply = @discussion.replies.find(params[:id])
     @reply.destroy
     redirect_to discussion_path(@discussion)
   end

   def edit
     @discussion = Discussion.friendly.find(params[:discussion_id])
     @reply = @discussion.replies.find(params[:id])
   end

   def update
     @reply = @discussion.replies.find(params[:id])
      respond_to do |format|
       if @reply.update(reply_params)
         format.html { redirect_to discussion_path(@discussion), notice: 'Reply was successfully updated.' }
       else
         format.html { render :edit }
         format.json { render json: @reply.errors, status: :unprocessable_entity }
       end
     end
   end

   def show
   end

   private

   def set_discussion
     @discussion = Discussion.friendly.find(params[:discussion_id])
   end

   def set_reply
     @reply = Reply.friendly.find(params[:id])
   end

   def reply_params
     params.require(:reply).permit(:reply, :discussion_id)
   end
end

app/views/replies/_form.html.erb
<%= simple_form_for([@discussion, @discussion.replies.build], remote: true) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
    </div>
  </div>

  <%= f.button :submit, 'Leave a reply', class:'button is-info' %>
<% end %>

app/views/replies/_reply.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-48x48">
        <%= gravatar_image_tag(reply.user.email, class: ' border-radius-50', size: 48, alt: reply.user.username) %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= reply.user.username %></strong><br><small><%= time_ago_in_words(reply.created_at) %></small>
          <br>
          <%= markdown(reply.reply) %>
        </p>
      </div>
      <% if reply_author(reply) || has_role?(:admin)%>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <%= link_to edit_discussion_reply_path(reply.discussion,reply) do %>
            <span class="icon is-small"><i class="fa fa-pencil"></i></span>
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to [reply.discussion, reply],
              method: :delete, data: { confirm: 'Are you sure ?'} do %>
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
            <% end %>
          </a>
        </div>
      </nav>
      <% end %>
    </div>
  </article>
</div>

app/views/replies/create.js.erb
$("<%= escape_javascript(render(@reply)) %>").appendTo('#discussion-replies')

app/views/replies/edit.html.erb
<h1 class="title has-text-grey">Editing Reply</h1>

<%= simple_form_for([@discussion, @reply]) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
    </div>
  </div>

<%= f.button :submit, 'Update Reply', class:'button is-info' %>
<% end %>