config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :discussions do
    resources :replies
  end
  
  root to: "discussions#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  belongs_to :channel
  has_many :replies , dependent: :destroy

  validates :title, :content, presence: true
  resourcify

  extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]

    def should_generate_new_friendly_id?
      title_changed?
    end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :find_channels, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /discussions
  # GET /discussions.json
  def index
    if params[:search]
      @discussions = Discussion.where("LOWER(title) like ?", "%#{params[:search].downcase}%")
    else
    @discussions = Discussion.all.order('created_at desc')
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussions = Discussion.all.order('created_at asc')
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /discussions/1/edit
  def edit
  end
  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.friendly.find(params[:id])
    end

    def find_channels
      @channels = Channel.all.order('created_at desc')
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :content, :channel_id)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper

  def discussion_author(discussion)
    user_signed_in? && current_user.id == discussion.user_id
  end

  def reply_author(reply)
    user_signed_in? && current_user.id == reply.user_id
  end
  
end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
  <%= f.error_notification %>

    <div class="field">
      <div class="control">
        <%= f.input :title, require: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, require: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

      <div class="field">
        <label for="" class="label">Channel</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :channel_id, collection: @channels.map { |c| [c.channel, c.id] }, prompt: "Select channel"  %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.button :submit, class:'button is-info' %>
        </div>
      </div>

<% end %>

app/views/discussions/_sidebar.html.erb
<div class="column is-3 is-offset-1">
  <h3 class="title has-text-grey">Channels</h3>

  <ul class="list">
    <% @channels.each do |c| %>
    <li><%= link_to c.channel, c %></li>
      <% end %>
  </ul>
  <br>
  <% if has_role?(:admin) %>
  <%= link_to 'New Channel', new_channel_path, class:'button is-info' %>
  <% end %>
</div>

app/views/discussions/edit.html.erb
<h1 class="title is-3">Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

app/views/discussions/index.html.erb
<div class="columns">
  <%= render 'shared/discussions' %>
  <%= render 'sidebar' %>
</div>

app/views/discussions/new.html.erb
<h1 class="title is-size-3">New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<div class="columns">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey discussion-title"><%= @discussion.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-lighter">by <%= @discussion.user.username %> in <%= link_to @discussion.channel.channel, @discussion.channel %></h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <% if discussion_author(@discussion) %>
        <div class="buttons">
          <%= link_to 'Edit Discussion', edit_discussion_path(@discussion), class:'button' %>
          <%= link_to 'Delete', discussion_path(@discussion), method: :delete, data: { confirm: "Delete discussion?"}, class:'button' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="content"><%= markdown(@discussion.content) %></div>

    <h2 class="subtitle is-5 has-text-grey"><%= @discussion.replies.count %> Replies</h2>

    <div id="discussion-replies">
      <%= render @discussion.replies %>
    </div>

    <hr>
    <h3 class="subtitle is-3 has-text-grey">Leave a reply</h3>
    <% if user_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
     <p>To reply you need to <%= link_to 'Login', new_user_session_path %>.Don't have an account? <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>
  </div>
  <%= render 'sidebar' %>
</div>