config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :discussions do
    resources :replies
  end
  
  root to: "discussions#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discussions</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
      <% if flash[:notice] %>
        <div class="notification is-success global-notification">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
      <% end %>
       <nav class="navbar is-light" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <%= link_to root_path, class:"navbar-item" do %>
            <h1 class="title is-5">Discussions</h1>
          <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

        <div id="navbar" class="navbar-menu">
          <div class="navbar-end">
            <% if user_signed_in? %>
            <div class="navbar-item">
              <div class="field is-grouped">
                <%= link_to 'New Discussion', new_discussion_path , class:"button is-info" %>
              </div>
            </div>
            <div class="navbar-item">
              <div class="field has-addons">
             <%= form_tag discussions_path, method: :get do %>
             <div class="control">
               <%= text_field_tag :search, params[:search],class:"input", placeholder:"Find a Discussion" %>
            </div>
              <% end %>
          </div>
            </div>
            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
           <% else %>
           <div class="navbar-item">
            <div class="field is-grouped">

              <p class="control">
                <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
              </p>

              <div class="field has-addons">
             <%= form_tag discussions_path, method: :get do %>
             <div class="control">
               <%= text_field_tag :search, params[:search],class:"input", placeholder:"Find a Discussion" %>
            </div>
              <% end %>
            </div>

              <p class="control">
                <%= link_to "Sign In", new_user_session_path, class: "button is-light"%>
              </p>

              <p class="control">
                <%= link_to "Sign up", new_user_registration_path, class: "button is-light" %>
              </p>
            </div>
            </div>
            <% end %>

          </div>
      </div>
    </nav>

  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>
  </body>
</html>